=== sebastiangraf/jSCSI/bundles/target/src/main/resources/jscsi-target.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2012, University of Konstanz, Distributed Systems Group
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
        * Redistributions of source code must retain the above copyright
          notice, this list of conditions and the following disclaimer.
        * Redistributions in binary form must reproduce the above copyright
          notice, this list of conditions and the following disclaimer in the
          documentation and/or other materials provided with the distribution.
        * Neither the name of the University of Konstanz nor the
          names of its contributors may be used to endorse or promote products
          derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
    DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<xs:schema elementFormDefault="qualified" targetNamespace="http://www.jscsi.org/2010-04"
    xmlns="http://www.jscsi.org/2010-04" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Type for target name fitting the iSCSI naming reference. -->
    <xs:simpleType name="TargetNameType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="100" />
            <xs:pattern
                value="iqn\.[0-9]{4}-[0-9]{2}\.([a-z0-9\-])+(\.([a-z0-9\-])+)*\:([a-z0-9\-])+(\.([a-z0-9\-])+)*" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Type for port. -->
    <xs:simpleType name="TargetPortType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="65536" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Type for creating a storage, including a length of the fresh storage. -->
    <xs:complexType name="CreateType">
        <xs:attribute name="size" type="xs:double" default="0.5" />
    </xs:complexType>

    <!-- Type for file storage. -->
    <xs:complexType name="FileStorageType">
        <xs:sequence>
            <!-- Storage where the data of the target should be stored to. -->
            <xs:element name="Path" type="xs:string" default="storage.dat"
                minOccurs="1" maxOccurs="1" />
            <!-- Should a new storage created or not. -->
            <xs:choice>
                <xs:element name="DontCreate" />
                <xs:element name="Create" type="CreateType" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!--Over all configuration including targets and a global config. -->
    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TargetList" type="TargetList"
                    minOccurs="1" maxOccurs="1" />
                <xs:element name="GlobalConfig" type="GlobalConfig"
                    minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Just the target list. -->
    <xs:complexType name="TargetList">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Target" />
        </xs:sequence>
    </xs:complexType>

    <!-- Type for the global config. Note that most settings are part of 
        the negotiation and thereby not set over here. -->
    <xs:complexType name="GlobalConfig">
        <xs:sequence>
            <xs:element name="AllowSloppyNegotiation" type="xs:boolean"
                default="false" minOccurs="0" maxOccurs="1" />
            <xs:element name="Address" type="xs:string"
                minOccurs="0" maxOccurs="1" />
            <xs:element name="ExternalAddress" type="xs:string"
                minOccurs="0" maxOccurs="1" />
            <xs:element name="Port" type="TargetPortType"
                default="3260" minOccurs="0" maxOccurs="1" />
            <xs:element name="ExternalPort" type="TargetPortType"
                default="3260" minOccurs="0" maxOccurs="1" />
            <xs:element name="VendorID" type="xs:string"
                minOccurs="0" maxOccurs="1" />
            <xs:element name="ProductID" type="xs:string"
                minOccurs="0" maxOccurs="1" />
            <xs:element name="ProductRevisionLevel" type="xs:string"
                minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <!-- Single targets. -->
    <xs:complexType name="Target">
        <xs:sequence>
            <xs:element name="TargetName" type="TargetNameType"
                minOccurs="1" maxOccurs="1" />
            <xs:element name="TargetAlias" type="xs:string"
                minOccurs="0" maxOccurs="1" />
            <xs:choice>
                <xs:element name="SyncFileStorage" type="FileStorageType" />
                <xs:element name="AsyncFileStorage" type="FileStorageType" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== sebastiangraf/jSCSI/bundles/target/src/main/resources/jscsi-target.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Copyright (c) 2012, University of Konstanz, Distributed Systems Group 
	All rights reserved. Redistribution and use in source and binary forms, with 
	or without modification, are permitted provided that the following conditions 
	are met: * Redistributions of source code must retain the above copyright 
	notice, this list of conditions and the following disclaimer. * Redistributions 
	in binary form must reproduce the above copyright notice, this list of conditions 
	and the following disclaimer in the documentation and/or other materials 
	provided with the distribution. * Neither the name of the University of Konstanz 
	nor the names of its contributors may be used to endorse or promote products 
	derived from this software without specific prior written permission. THIS 
	SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
	ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
	IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY DIRECT, INDIRECT, 
	INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
	NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
	DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY 
	OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
	OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF y
	ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. -->

<configuration xmlns="http://www.jscsi.org/2010-04"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jscsi.org/2010-04 jscsi-target.xsd">

	<TargetList>
		<Target>
			<TargetName>box.vm:disk-1</TargetName>
			<!-- Optional, default to empty string "". -->
			<TargetAlias>jSCSI Target</TargetAlias>
			<!--
			Available storage:
			* AsyncFileStorage  - Implemented by RandomAccessStorageModule class.
			                      Access the storage file by java.io.RandomAccessFile, opened in "rwd" mode,
			                      which requires that every update to the file's content be written synchronously
			                      to the underlying storage device.
			* SyncFileStorage   - Implemented by SynchronizedRandomAccessStorageModule class.
			                      Adds synchronized keyword around read, write methods.
			* JCloudsStorage    - Implemented by JCloudsStorageModule class.
			* ExtendedStorage   - Implemented by a class specified in the class attribute. e.g.
			                      <ExtendedStorage class="my.pretty.ExStorageModule">
			                      The class implements IStorageModule interface, and a constructor with two parameters
			                      (long lStorageLengthIn512BytesBlocks, File fStorageMedium).
			-->
			<AsyncFileStorage>
				<Path>/tmp/vbox.dat</Path>
				<!--
				<NoCreate />
				or
				<Create size="{size in GB}"/>
				e.g. <Create size="1"/> will create 1 GB storage file automatically.
				-->
				<NoCreate />
			</AsyncFileStorage>
		</Target>
		<Target>
			<TargetName>iqn.2010-04.local-test:disk-1</TargetName>
			<TargetAlias>jSCSI Target</TargetAlias>
			<AsyncFileStorage>
				<Path>/tmp/storage1.dat</Path>
				<NoCreate />
			</AsyncFileStorage>
		</Target>
		<Target>
			<TargetName>iqn.2010-04.local-test:disk-2</TargetName>
			<TargetAlias>jSCSI Target</TargetAlias>
			<AsyncFileStorage>
				<Path>/tmp/storage2.dat</Path>
				<NoCreate />
			</AsyncFileStorage>
		</Target>
	</TargetList>
	<GlobalConfig>
		<AllowSloppyNegotiation>true</AllowSloppyNegotiation>
		<!--
		Target server listening address,
		optional, default to local host address returned by java.net.InetAddress.getLocalHost()
		-->
		<Address>0.0.0.0</Address>
		<!--
		Listening address returned to iSCSI initiator,
		optional, default to local host address returned by java.net.InetAddress.getLocalHost()
		-->
		<ExternalAddress>127.0.0.1</ExternalAddress>
		<!--
		Target server listening port,
		optional, default to 3260 according to the iSCSI protocol.
		-->
		<Port>3260</Port>
		<!--
		Listening port returned to iSCSI initiator,
		optional, default to 3260 according to the iSCSI protocol.
		-->
		<ExternalPort>3260</ExternalPort>
		<!--
		Optional, no more than  8 ASCII characters, automatically truncated if too long,
		see StandardInquiryData class for default value.
		-->
		<VendorID>jSCSIorg</VendorID>
		<!--
		Optional, no more than 16 ASCII characters, automatically truncated if too long,
		see StandardInquiryData class for default value.
		-->
		<ProductID>iSCSI target</ProductID>
		<!--
		Optional, no more than  4 ASCII characters, automatically truncated if too long,
		see StandardInquiryData class for default value.
		-->
		<ProductRevisionLevel>1.00</ProductRevisionLevel>
	</GlobalConfig>
</configuration>
